#file: noinspection YAMLSchemaValidation

###
### Required configuration for all plugins
###

# A name for the plugin
name: Mumble auth

# Full class name of class implementing Neucore\Plugin\ServiceInterface.
phpClass: Neucore\Plugin\Mumble\Service

# PHP namespace that should be loaded by the PSR-4 autoloader.
psr4Prefix: Neucore\Plugin\Mumble

# Relative (to this file) path to the directory containing the classes of the above namespace.
psr4Path: src


###
### Required configuration for service plugins
###

# Defines if this service allows only one account per player instead of one per character.
oneAccount: false

# List of available account properties, possible values: username, password, email, status, name
properties:
  - username
  - password

# If this is not enabled and the account contains a password (see properties), the user will be able to see
# it only once after it is reset (see actions).
showPassword: true

# List of actions, possible values: update-account, reset-password
actions:
  - update-account
  - reset-password


###
### Optional configuration for all plugins
###

# Additional configuration for the plugin (supports multiline text).
configurationData: |
  Nickname: '{corporationTicker} - {characterName} [{allianceTicker}] ({tags})'
  GroupsToTags:
    alliance.leadership: Leadership
    alliance.fleet-commander: FC
    alliance.ceo: CEO
    pronoun.he: He/Him
    pronoun.she: She/Her
    pronoun.they: They/Them
  MainTagReplacesCorporationTicker: false
  BannedGroup: 18 # Optional Neucore group ID, members of this group will not be able to connect.
  AdditionalTagGroups: # Optional
    -
      - He/Him
      - She/He
      - She/Her
      - They/Them
      - He/They
      - She/They
      - Any Pronouns
    -
      - CEO

###
### Optional configuration for service plugins
###

# List of link buttons. Placeholders for URL: {plugin_id}, {username}, {password}, {email}
URLs:
  -
    url: https://www.mumble.info/
    title: Download Mumble
    target: _blank
  -
    url: mumble://{username}:{password}@mumble.your-server.tdl:64738/?version=1.3.0&title=Yours Comms
    title: Connect to Mumble
    target: _self

# Text above the list of accounts (supports multiline text).
textTop:

# Text below account table (supports multiline text).
textAccount: |
  Manual Configuration
  Address: mumble.your-server.tdl
  Port: 64738

# Text below the registration form/button (supports multiline text).
textRegister:

# Text below an account with status "pending" (supports multiline text).
textPending:
